### ISSUE TITLE
Problems running Unima

### ISSUE THREAD

**Issue by jnyrup** [Testura/Testura.Mutation#1]
I'm trying to run Unima (downloaded binary from GitHub) from PowerShell, but I'm struggling to get it to work.

The output:
```
2019-05-17 11:05:09,096: Unima.Application.Commands.Project.OpenProject.OpenProjectCommandHandler: Opening project at C:\Users\jonas\Downloads\mutation\config.json
2019-05-17 11:05:09,127: Unima.Application.Commands.Project.OpenProject.OpenProjectCommandHandler: Loading configuration: {
    "SolutionPath":  "C:\\git\\fluentassertions\\FluentAssertions.sln",
    "TestProjects":  [
                         "C:\\git\\fluentassertions\\Tests\\NetCore20.Specs\\NetCore20.Specs.csproj"
                     ],
    "BuildConfiguration":  "Debug",
    "TestRunner":  "dotnet",
    "NumberOfTestRunInstances":  5,
}
2019-05-17 11:05:09,595: Unima.Application.Commands.Project.OpenProject.OpenProjectCommandHandler: Failed to open project
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.MSBuildMefHostServices.get_DefaultServices()
   at Unima.Application.Commands.Project.OpenProject.OpenProjectCommandHandler.<Handle>d__2.MoveNext()
```

The project I'm trying to test:
https://github.com/fluentassertions/fluentassertions/

Any hints?

**Comment by MilleBo** [comment]
I downloaded your project and tried to open it myself and managed to get passed the point you failed at. But it still fail later on when compiling because of different System.RunTime versions:

"Assembly 'FluentAssertions' with identity 'FluentAssertions, Version=5.0.1.0, Culture=neutral, PublicKeyToken=33f2691a05b67b6a' uses 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'"

So I will try to take a look at it this weekend and see why Roslyn won't handle it.

**Comment by jnyrup** [comment]
Thanks for taking the time.
I haven't been able to compile the project in Visual Studio 2019 myself so far, but If you have any builds that I can run to help, feel free to reach out.

**Comment by MilleBo** [comment]
A bit of an update: 

It seems like roslyn fail to build all your Core 1.1 projects because your main project only target Core 2.0. I found a couple of issues on this on the roslyn repo but sadly it doesn't seem to have that high priority👎 

I will maybe try to look for some other solution or see if I do something wrong but I don't think there are a quick fix for now.

**Comment by MilleBo** [comment]
This is a problem with multiple target frameworks. It should work with the latest version (easiest are to try it with the visual studio extension).,
